---
browser: "phantomjs"

directory: "shots"

domains:
  production: https://www.gov.uk
  staging: https://www-origin.staging.publishing.service.gov.uk

screen_widths:
  - 1024

fuzz: 20%

mode: diffs_first

threshold: 5

verbose: true
